export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

export const TOGGLE_DARK_MODE = 'TOGGLE_DARK_MODE';
export const TOGGLE_MENU = 'TOGGLE_MENU';

export const GET_COUNTRIES = 'GET_COUNTRIES';
export const GET_COUNTRIES_SUCCESS = 'GET_COUNTRIES_SUCCESS';
export const GET_COUNTRIES_FAIL = 'GET_COUNTRIES_FAIL';

export const GET_IMAGE = 'GET_IMAGE';
export const GET_IMAGE_SUCCESS = 'GET_IMAGE_SUCCESS';
export const GET_IMAGE_FAIL = 'GET_IMAGE_FAIL';

export const GET_COUNTRY_IMAGES = 'GET_IMAGES';
export const GET_COUNTRY_IMAGES_SUCCESS = 'GET_IMAGES_SUCCESS';
export const GET_COUNTRY_IMAGES_FAIL = 'GET_IMAGES_FAIL';

export const ADD_COUNTRY = 'ADD_COUNTRY';
export const ADD_COUNTRY_SUCCESS = 'ADD_COUNTRY_SUCCESS';
export const ADD_COUNTRY_FAIL = 'ADD_COUNTRY_FAIL';

export const ADD_IMAGE = 'ADD_IMAGE';
export const ADD_IMAGE_SUCCESS = 'ADD_IMAGE_SUCCESS';
export const ADD_IMAGE_FAIL = 'ADD_IMAGE_FAIL';

export const CHANGE_SCREEN_SIZE = 'CHANGE_SCREEN_SIZE';